# Generated by Django 2.2 on 2020-08-09 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.CharField(max_length=50)),
                ('skills', models.CharField(max_length=50)),
                ('pdff', models.FileField(upload_to='')),
            ],
        ),
    ]
